// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _platformOptions['web']!;

    return _platformOptions[defaultTargetPlatform] ??
        (throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform: $defaultTargetPlatform',
        ));
  }

  static const Map<dynamic, FirebaseOptions> _platformOptions = {
    TargetPlatform.android: FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-messaging-sender-id',
      projectId: 'your-project-id',
      storageBucket: 'your-storage-bucket',
    ),
    TargetPlatform.iOS: FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-messaging-sender-id',
      projectId: 'your-project-id',
      storageBucket: 'your-storage-bucket',
      iosBundleId: 'com.example.yourproject',
    ),
    TargetPlatform.macOS: FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-messaging-sender-id',
      projectId: 'your-project-id',
      storageBucket: 'your-storage-bucket',
      iosBundleId: 'com.example.yourproject',
    ),
    TargetPlatform.windows: FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-messaging-sender-id',
      projectId: 'your-project-id',
      authDomain: 'your-auth-domain',
      storageBucket: 'your-storage-bucket',
      measurementId: 'your-measurement-id',
    ),
    'web': FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-messaging-sender-id',
      projectId: 'your-project-id',
      authDomain: 'your-auth-domain',
      storageBucket: 'your-storage-bucket',
      measurementId: 'your-measurement-id',
    ),
  };
}

